baseURL = "https://rgalliher.com/"
languageCode = "en-us"
title = "Ryan Galliher"
theme = "PaperMod"

[params]
    defaultTheme = "dark"
    # Profile Mode settings (The Homepage)
    [params.profileMode]
        enabled = true
        title = "Hi, I'm Ryan Galliher"
        subtitle = "This my life's data. Feel free to copy it!"
        imageUrl = "/images/profile.png"
        imageTitle = "Human Subject"
        imageWidth = 150
        imageHeight = 150

        # Friendly Buttons
        [[params.profileMode.buttons]]
            name = "ðŸŒŠ Read the Journey"
            url = "/logs"

        [[params.profileMode.buttons]]
            name = "ðŸ¤– See the AI Analysis"
            url = "/ai-logs" # You can filter tags later

[params.homeInfoParams]
    Title = "N=1"
    Content = "Welcome to the experiment."

[menu]
    [[menu.main]]
        identifier = "logs"
        name = "Training Logs"
        url = "/logs/"
        weight = 10