baseURL = "https://ryan-galliher.com/"
languageCode = "en-us"
title = "Ryan Galliher"
theme = "PaperMod"

[params]
    defaultTheme = "light"
    disableThemeToggle = true
    # Profile Mode settings (The Homepage)
    [params.profileMode]
        enabled = true
        title = "Hi, I'm Ryan"
        subtitle = "and I'm designing my future self"
        imageUrl = "/images/profile.png"
        imageTitle = "Human Subject"
        imageWidth = 175
        imageHeight = 175

        # Friendly Buttons
        [[params.profileMode.buttons]]
            name = "the past self"
            url = "/logs"

        [[params.profileMode.buttons]]
            name = "the progress over time"
            url = "/ai-logs" # You can filter tags later
        
        [[params.profileMode.buttons]]
            name = "wait what is this?"
            url = "/about"
[params.homeInfoParams]
    Title = "N=1"
    Content = "Welcome to the experiment."

[menu]
    [[menu.main]]
        identifier = "logs"
        name = "Training Logs"
        url = "/logs/"
        weight = 10