baseURL = "https://rgalliher.com/"
languageCode = "en-us"
title = "Zenith Self"
theme = "ink-free"
paginate = 5

copyright = "Â© Copyright notice"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Finding your Zenith Self 100 hours at a time" 

	# Optional 64x64 avatar image.
	avatar = "/images/profile-compressed.jpg"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "auto"

	# Enable a table of contents
	toc = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	# Github base url
	github = "https://github.com/chollinger93/ink-free"


# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/chollinger93/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 